### ISSUE TITLE
More details on usage?

### ISSUE THREAD

**Issue by chong1144** [DragonRollGH/AutoChisai_TJ#1]
可以介绍一下那几个表项的获取方式吗？比如，Authorization 和 studentPid 以及 Receivers

**Comment by DragonRollGH** [comment]
用微信PC端打开打卡小程序，然后用网络抓包工具可以直接抓取到所有项。
私信 dr-tj@outlook.com

**Comment by chong1144** [comment]
thx!

**Comment by DragonRollGH** [comment]
其中IP是用于XFF头的代理IP；Receivers是用于接收每日自动打卡结果的邮箱，邮件功能还需要配置发件人smtp服务。

> 用微信PC端打开打卡小程序，然后用网络抓包工具可以直接抓取到所有项。
> 私信 [dr-tj@outlook.com](mailto:dr-tj@outlook.com)
